services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  webserver:
    image: apache/airflow:2.9.1-python3.10
    restart: always
    depends_on: [postgres]
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    volumes:
      - ../airflow-dags:/opt/airflow/dags
    ports:
      - 8080:8080
    command: webserver

  scheduler:
    image: apache/airflow:2.9.1-python3.10
    restart: always
    depends_on: [webserver]
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ../airflow-dags:/opt/airflow/dags
    command: scheduler

# run once: docker compose -f docker/docker-compose.yml run --rm webserver airflow db migrate
# to start the services: docker compose -f docker/docker-compose.yml up -d